/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yzsAdXjw1Ew
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export default function Component() {
  return (
    <div className="grid grid-cols-3 gap-4 h-screen">
      <div className="col-span-2 bg-white dark:bg-gray-800 overflow-y-auto">
        <div className="p-4 space-y-4">
          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Oct 08, 2023 9:15 AM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
              I got fired from work.
            </p>
          </div>
          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Lawbot</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:20 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Your Avatar" src="/placeholder-user.jpg" />
                <AvatarFallback>L</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">Question 1: Can you provide the reason your employer gave for terminating your employment?</p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:20 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            The reason was that I was underperforming.
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Lawbot</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:21 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>L</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            Question 2: Do you disagree with the statement that you were underperforming and, if so, can you provide any evidence to support your stance? 
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:21 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            I may have underperformed since I had 3 bad months.
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Lawbot</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:22 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>L</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
              Question 3: Were you provided with any warnings or given a chance to improve your performance before being terminated?
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:22 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            No, I wasn't provided any warnings or given a chance to improve.
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Lawbot</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:22 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>L</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            Question 4: Did you have an employment contract, and if so, does it specify the terms and conditions for termination? If you do have a contract, it would be beneficial to review it.
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:23 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            I have an employment contract. I am not sure what it specifies.
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Lawbot</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:23 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>L</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            Question 5: Can you please obtain a copy of your employment contract and check if there are any clauses concerning performance expectations and termination procedures? If you have already done this, what have you found?
            </p>
          </div>

          <div className="flex items-start justify-between">
            <div className="flex flex-col space-y-2">
              <div className="text-sm font-semibold">Elvis Bektashi</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Jan 22 , 2024 9:23 PM</div>
            </div>
            <div className="ml-4">
              <Avatar>
                <AvatarImage alt="Olivia Davis" src="/placeholder-user.jpg" />
                <AvatarFallback>EB</AvatarFallback>
              </Avatar>
            </div>
          </div>
          <div className="pl-14">
            <p className="text-sm">
            I will attach my findings in the user portal.
            </p>
          </div>
          
        </div>
      </div>
      <div className="bg-gray-100 dark:bg-gray-800 p-4 space-y-4">
        <Button className="w-full">Contact</Button>
        <Button className="w-full">Add Files</Button>
        <Button className="w-full">View Case Summary</Button>
        <Button className="w-full">Next Steps</Button>
      </div>
    </div>
  )
}
